# ------------------------------
# hugo config
# ------------------------------

title = "Shiro Ikeda website"
baseURL = "https://ikeda46.github.io"
defaultContentLanguage = "en"
canonifyURLs = "true"
#relativeURLs = "true"

[author]
name = "Shiro Ikeda"
email = "shiro@ism.ac.jp"

[build]
noJSConfigInAssets = true

[languages.ja]
weight = 2
languageCode = "ja"
languageName = "Ja"
hasCJKLanguage = true
summaryLength = 100

[languages.en]
weight = 1
languageCode = "en"
languageName = "En"
hasCJKLanguage = false
summaryLength = 100
